# Get Posts
GET http://localhost:4000/post
###
# Create Post
POST http://localhost:4000/post
Content-Type: application/json

{ "title": "first post", "sender": "chang", "content": "my life is a lie" }
###
# Get Comments
GET http://localhost:4000/comment
###
# Get Comments
GET http://localhost:4000/comment/695579965c2cd7f5d0d3a9af
###
# Create Post
POST http://localhost:4000/comment
Content-Type: application/json

{ "postId": "695696c58e15f542f41a8f4f", "sender": "chang", "content": "your life is a lie" }
###